sudo: required

dist: trusty

language: node_js

node_js:
  - "7"
  - "6"
  - "5"
  - "4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common -y -qq
  - sudo add-apt-repository -y ppa:puffscoin/puffscoin
  - sudo add-apt-repository -y ppa:puffscoin/puffscoin-dev
  - sudo apt-get update -qq
  - sudo apt-get install gpuffs -y -qq
  - yes | gpuffs --datadir ~/.puffscoin-10101 &
  - sleep 5
  - killall gpuffs
  - yes | gpuffs --datadir ~/.puffscoin-7 &
  - sleep 5
  - killall gpuffs
  - npm install -g npm

install:
  - npm install
  - npm install jshint

script:
  - npm run lint
  - travis_wait 60 istanbul cover -x **/lib/** ./node_modules/mocha/bin/_mocha test/*.js --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
